language: php
sudo: required
services:
  - mysql
php:
  - '7.3'
  - '7.2'
branches:
    only:
        - master
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test_db; use test_db;'
install: ./travis.sh
env:
  - CI_ENV="testing"
script:
  - composer require phpunit/phpunit
  - ./vendor/bin/phpunit
