language: php
sudo: required
services:
- mysql
php:
- '7.3'
- '7.2'
branches:
  only:
  - master
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS test_db;'
install: "./travis.sh"
env:
  global:
  - CI_ENV="testing"
  - TRAVIS="true"
  - TRAVIS_JOB_ID="$TRAVIS_JOB_ID"
  - CI_BUILD_NUMBER="$TRAVIS_BUILD_NUMBER"
  - CI_PULL_REQUEST="$TRAVIS_PULL_REQUEST"
  - CI_BRANCH="$TRAVIS_BRANCH"
  - secure: sFwS9Xa4ftAY3JN3gxr+rulukHn14DfVJVhAqzjlBlbXl4knR9jeHQ5bT/N+0Lg/FR0kOWaioH1W9SnoanIiEKNbgsBl46oJVDNlTv20AXKzpYQjfDBl8U6DWFEl7mXrKqeMhW99XntLZGPG2aHFlcORp39l84J2JHoFP2vTSuEKni1vuoz2K4eFO9j45bgP2DS/1uRC0JSyBdXprmYcTfMFgju2s0qpub0I/pN9h+nEF54yYar7OXvI0nimcR40cz07UNQRadbVokqHM77mtJxrmz9latkTT6bmUnWmE21dkMfNsCUUv1WidAUmOQiB2zbOUwFjl9ZZ9Yim7LaIhrmq29nztKGpWe7mjUPO+6HTZ5MxGfgHiTCRlRYhKXok2zxUVjeuqX3sNfAQYnCueTv+d+mWCIbcBzfqJKPbx1m566IcZdhyxdwmdvC6TQnDN9cKd5xdTecceXaXc72CpmskdM0WtQdcIUSuCyfsyRMksAmPWH6Uqa920DkSps0KbBhOK0NHKimQx9HTjuO/L/K7YQVI328cbzxkGEWGyuGgKLpMD+KDFsz4vmYaCzmDE6WaUKs06wqRZS8wSKBzDws3EVKQQM4Ha3Zdz/8Y5wIzLh4WIRq5kMJIlH4qw4HmsC1p1MHmYspUhniTq3M+64PoTPaWA0tNSZwQNxbytUs=
script:
- composer require php-coveralls/php-coveralls
- phpunit
after_success:
- travis_retry php vendor/bin/php-coveralls -v
